-- ============================================================================
-- TrainerCore seed — global exercise library (50 exercises).
-- Runs on `supabase db reset`. The demo trainer + UAE demo data are created by
-- `pnpm seed` (scripts/seed.ts), which uses the Auth admin API.
-- ============================================================================

insert into exercises (name, muscle_group, equipment, instructions) values
('Barbell Bench Press','chest','Barbell','Lie on a flat bench, lower the bar to mid-chest and press up to full extension.'),
('Incline Dumbbell Press','chest','Dumbbells','On a 30-45 degree incline bench, press dumbbells from shoulder level to overhead.'),
('Push-Up','chest','Bodyweight','Keep a straight line from head to heels, lower chest to the floor and press up.'),
('Cable Fly','chest','Cable Machine','With a slight forward lean, bring both handles together in a hugging arc.'),
('Dumbbell Bench Press','chest','Dumbbells','Press dumbbells from chest level to lockout, controlling the descent.'),
('Chest Dip','chest','Parallel Bars','Lean slightly forward and lower until elbows reach 90 degrees, then press up.'),
('Machine Chest Press','chest','Machine','Press the handles forward to full extension and return under control.'),
('Conventional Deadlift','back','Barbell','Hinge at the hips, keep a flat back and drive through the floor to stand tall.'),
('Pull-Up','back','Pull-Up Bar','Hang with an overhand grip and pull until the chin clears the bar.'),
('Bent-Over Barbell Row','back','Barbell','Hinge to about 45 degrees, row the bar to the lower ribs and squeeze the shoulder blades.'),
('Lat Pulldown','back','Cable Machine','Pull the bar to the upper chest while keeping the torso upright.'),
('Seated Cable Row','back','Cable Machine','Pull the handle to the abdomen, keeping the chest up and back flat.'),
('Single-Arm Dumbbell Row','back','Dumbbell','Brace on a bench and row the dumbbell to the hip, controlling the stretch.'),
('Face Pull','back','Cable Machine','Pull the rope toward the face, leading with the elbows to hit the rear delts.'),
('Back Squat','legs','Barbell','Bar on upper back, squat to at least parallel and drive up through mid-foot.'),
('Front Squat','legs','Barbell','Bar racked on the front delts, squat upright and keep elbows high.'),
('Leg Press','legs','Machine','Lower the platform until knees reach about 90 degrees, then press without locking out hard.'),
('Romanian Deadlift','legs','Barbell','Hinge with soft knees, slide the bar down the thighs and feel the hamstrings.'),
('Walking Lunge','legs','Dumbbells','Step forward into a lunge until the rear knee nearly touches, then alternate.'),
('Leg Extension','legs','Machine','Extend the knees to straighten the legs, pausing briefly at the top.'),
('Lying Leg Curl','legs','Machine','Curl the pad toward the glutes, controlling the eccentric.'),
('Standing Calf Raise','legs','Machine','Rise onto the balls of the feet, pause at the top and lower under control.'),
('Overhead Barbell Press','shoulders','Barbell','Press the bar from the front delts to overhead lockout without leaning back.'),
('Dumbbell Shoulder Press','shoulders','Dumbbells','Press dumbbells from shoulder height to overhead, keeping the core tight.'),
('Lateral Raise','shoulders','Dumbbells','Raise the dumbbells out to the sides to shoulder height with a slight bend.'),
('Front Raise','shoulders','Dumbbells','Lift the dumbbells forward to shoulder height, avoiding momentum.'),
('Rear Delt Fly','shoulders','Dumbbells','Hinge forward and raise the dumbbells out to the sides, squeezing rear delts.'),
('Arnold Press','shoulders','Dumbbells','Rotate from a palms-in start to press overhead with palms forward.'),
('Upright Row','shoulders','Barbell','Pull the bar up along the body to chest height, leading with the elbows.'),
('Barbell Biceps Curl','arms','Barbell','Curl the bar to shoulder level, keeping elbows pinned to the sides.'),
('Dumbbell Hammer Curl','arms','Dumbbells','Curl with a neutral grip to target the brachialis and forearms.'),
('Triceps Pushdown','arms','Cable Machine','Push the bar down to full extension, keeping elbows tucked.'),
('Overhead Triceps Extension','arms','Dumbbell','Lower the dumbbell behind the head and extend to lockout.'),
('Preacher Curl','arms','EZ Bar','Curl over the preacher pad through a full range without swinging.'),
('Close-Grip Bench Press','arms','Barbell','Press with a shoulder-width grip to emphasise the triceps.'),
('Concentration Curl','arms','Dumbbell','Seated with the elbow braced on the thigh, curl with a peak contraction.'),
('Plank','core','Bodyweight','Hold a straight line on the forearms, bracing the abs and glutes.'),
('Hanging Leg Raise','core','Pull-Up Bar','Hang and raise the legs to hip height or higher without swinging.'),
('Cable Crunch','core','Cable Machine','Kneel and crunch the torso down, rounding through the abs.'),
('Russian Twist','core','Medicine Ball','Seated with feet up, rotate the torso side to side under control.'),
('Bicycle Crunch','core','Bodyweight','Alternate elbow-to-opposite-knee while extending the other leg.'),
('Ab Wheel Rollout','core','Ab Wheel','Roll out as far as control allows while keeping the spine neutral.'),
('Mountain Climber','core','Bodyweight','From a plank, drive the knees toward the chest in a running motion.'),
('Treadmill Run','cardio','Treadmill','Steady-state or interval running at a target pace or incline.'),
('Rowing Machine','cardio','Rower','Drive with the legs, then pull with the back and arms in sequence.'),
('Assault Bike','cardio','Air Bike','Push and pull the handles while driving the pedals for full-body cardio.'),
('Jump Rope','cardio','Skipping Rope','Maintain a steady bounce, turning the rope from the wrists.'),
('Stair Climber','cardio','Machine','Climb at a steady cadence keeping an upright posture.'),
('Battle Ropes','cardio','Battle Ropes','Create alternating or simultaneous waves while staying in a quarter-squat.'),
('Burpees','cardio','Bodyweight','Drop to a push-up, jump the feet in and explode into a vertical jump.')
on conflict do nothing;
